### ISSUE TITLE
Implement the TextInput and TextBox widget.

### ISSUE THREAD

**Issue by aoitofu** [thoth-42/MILK#4]
Now MILK has no way to get any string user input. It is necessary for GUI.

## ToDo
- [x] Implement the focus system. (like tracking system)
- [x] Add new signal to class Widget for handling the SDL_TEXTINPUT event.
- [ ] Add new widgets TextInput and TextBox.

**Comment by thoth-42** [comment]
Started refactoring.
